### ISSUE TITLE
run-time error

### ISSUE THREAD

**Issue by jinzhi666** [jzyustc/MBRS#7]
```txt
save_images_number = 4
H = 128
W = 128
message_length = 30
lr = 0.001
noise_layers = ['Combined([JpegMask(50),Jpeg(50),Identity()])']

0.001

Start training : 


Traceback (most recent call last):
  File "train.py", line 55, in <module>
    result = network.train(image, message) if not only_decoder else network.train_only_decoder(image, message)
  File "/home/admin/code/Watermarking/MBRS/network/Network.py", line 53, in train
    encoded_images, noised_images, decoded_messages = self.encoder_decoder(images, messages)
  File "/home/admin/miniconda3/envs/torch15_py37_ljz/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/admin/miniconda3/envs/torch15_py37_ljz/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/admin/miniconda3/envs/torch15_py37_ljz/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/admin/code/Watermarking/MBRS/network/Encoder_MP_Decoder.py", line 19, in forward
    encoded_image = self.encoder(image, message)
  File "/home/admin/miniconda3/envs/torch15_py37_ljz/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/admin/code/Watermarking/MBRS/network/Encoder_MP.py", line 39, in forward
    message_image = message.view(-1, 1, size, size)
RuntimeError: shape '[-1, 1, 5, 5]' is invalid for input of size 480


```

my train_settings.json

```json
{
  "project_name": "MBRS",
  "with_diffusion": false,
  "only_decoder": false,
  "epoch_number": 101,
  "batch_size": 16,
  "train_continue": false,
  "train_continue_path": "/",
  "train_continue_epoch": 0,
  "dataset_path": "/home/admin/code/Watermarking/data/",
  "save_images_number": 4,
  "H": 128,
  "W": 128,
  "message_length": 30,
  "lr": 1e-3,
  "noise_layers": [
    "Combined([JpegMask(50),Jpeg(50),Identity()])"
  ]
}
```

my conda

```txt
torch==1.5.0
torchvision==0.6.0
kornia 0.3.0
cuda10.1
python3.7
```

**Comment by jzyustc** [comment]
Hi, `message_length=30` is not supported for `with_diffusion=false`. When diffusion block is disabled, the message length should be like $x^2$, e.g., $8^2=64$. 

You can kindly set `message_length=30, with_diffusion=true` or `message_length=64, with_diffusion=false` to solve it.

**Comment by jinzhi666** [comment]
Thank you very much for helping me solve this problem

> Hi, `message_length=30` is not supported for `with_diffusion=false`. When diffusion block is disabled, the message length should be like x2, e.g., 82=64.
> 
> You can kindly set `message_length=30, with_diffusion=true` or `message_length=64, with_diffusion=false` to solve it.

Thank you very much for helping me solve this problem!
